/**
 * Language Context — Multilingual support for the Danubian Federation website
 * Default: German (de), with English, French, Hungarian, Czech, Croatian
 */
import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type Language = "de" | "en" | "fr" | "hu" | "cs" | "hr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

// Translation dictionary — Home page (Option B: only Home translated for now)
const translations: Record<Language, Record<string, string>> = {
  de: {
    // Nav
    "nav.home": "Startseite",
    "nav.history": "Geschichte",
    "nav.family": "Die Kaiserliche Familie",
    "nav.traditions": "Traditionen",
    "nav.heraldry": "Heraldik",
    "nav.properties": "Kaiserliche Residenzen",
    "nav.world": "Die Welt",
    "nav.constitution": "Verfassung",
    "nav.books": "Der Donau-Thron",
    "nav.press": "Presse",
    // Header
    "header.imperialHouse": "Kaiserliches Haus",
    // Hero
    "hero.pretitle": "Gegr. MCMXVII · Neustadt, Donau",
    "hero.title1": "Kaiserliches Haus",
    "hero.title2": "Österreich-Donau",
    "hero.subtitle": "Hüter der Donau. Erben eines Jahrtausends.",
    "hero.cta1": "Unsere Geschichte",
    "hero.cta2": "Die Kaiserliche Familie",
    "hero.scroll": "Scrollen",
    // Announcement
    "announcement": "✦   Kaiserliche Bekanntmachung: Die Verlobung von Kronprinz Leopold von Habsburg und Fräulein Katharina von Richter wird hiermit feierlich verkündet — Frühling 2026   ✦",
    // About
    "about.section": "I · Das Haus",
    "about.title1": "Eine Dynastie geboren",
    "about.title2": "aus Adler und Fluss",
    "about.p1": "Das Kaiserliche Haus Österreich-Donau ist die Fortführung des altehrwürdigen Hauses Habsburg-Lothringen, einer der erhabensten Dynastien der europäischen Geschichte. Seine Wurzeln reichen zurück zu den mittelalterlichen Grafen von Habsburg und den Jahrhunderten der Kaiser des Heiligen Römischen Reiches, Könige von Ungarn und Böhmen und Erzherzöge von Österreich. Im Jahr 1914 scheiterte das Attentat auf Erzherzog Franz Ferdinand in Sarajevo — der Erzherzog überlebte, und die europäische Krise wurde am Verhandlungstisch gelöst, nicht auf dem Schlachtfeld. Der Vertrag von Wien von 1917 verwandelte die Österreichisch-Ungarische Monarchie in die Donauföderation: eine konstitutionelle Konföderation von fünfzehn Staaten, vereint unter der Kaiserkrone.",
    "about.p2": "Heute, unter der Regentschaft Seiner Kaiserlichen und Königlichen Apostolischen Majestät Kaiser Maximilian I. — nun im neunzehnten Jahr auf dem Thron — dient das Haus weiterhin als konstitutioneller Souverän der Donaukonföderation und regiert über fünfzehn Staaten und mehr als achtzig Millionen Bürger mit Würde, Tradition und unerschütterlichem Engagement für die Völker der Flussländer.",
    "about.link": "Die vollständige Geschichte lesen →",
    // Emperor
    "emperor.section": "II · Der Souverän",
    "emperor.title": "Seine Kaiserliche Majestät",
    "emperor.caption": "Seine Kaiserliche Majestät Maximilian I.\nKaiser von Österreich-Donau · 19 Jahre auf dem Thron",
    "emperor.p1": "Geboren 1954 in der Hofburg in Wien, bestieg Maximilian Franz Josef Karl von Österreich-Donau den Kaiserthron nach dem Ableben seines Vaters. Er regiert nun seit siebenunddreißig Jahren und präsidiert über eine Epoche der konstitutionellen Konsolidierung und europäischen Integration.",
    "emperor.p2": "Seine Majestät hat seine Pflichten mit unerschütterlicher Würde angesichts tiefgreifender persönlicher Tragödie getragen. Die verstorbene Kaiserin Maria-Cristina kam bei dem Brand im Pariser Ritz am 10. September 2000 ums Leben — ein Verlust, der die Konföderation und die Welt erschütterte. Seither hat er sich ganz seinem Volk gewidmet. Die bevorstehende Vermählung von Kronprinz Leopold mit Katharina von Richter ist ein Moment großer Freude für das Kaiserliche Haus und die Konföderation gleichermaßen.",
    "emperor.titles.label": "Vollständiger Stil & Titel",
    "emperor.titles.text": "Seine Kaiserliche und Königliche Majestät Maximilian I., von Gottes Gnaden Kaiser von Österreich-Donau, König der Donauländer, Erzherzog von Neustadt, Großherzog der Ostmarken, Beschützer der Flussvölker, Ritter des Ordens vom Goldenen Adler.",
    "emperor.link": "Die Kaiserliche Familie kennenlernen →",
    // Pillars
    "pillars.section": "III · Unsere Grundlagen",
    "pillars.title": "Die drei Säulen des Hauses",
    "pillars.tradition.title": "Tradition",
    "pillars.tradition.text": "Seit 1917 pflegt das Kaiserliche Haus die zeremoniellen Traditionen der Donaukonföderation — vom jährlichen Fest des Adlers bis zur feierlichen Proklamation des Kaisers vom Balkon der Hofburg und der altehrwürdigen ungarischen Krönung in Budapest.",
    "pillars.honour.title": "Ehre",
    "pillars.honour.text": "Der Orden vom Goldenen Adler, gegründet 1917 bei der Proklamation der Donauföderation, bleibt die höchste Auszeichnung, die der Kaiser verleihen kann. Zu seinen Trägern zählen Staatsmänner, Gelehrte und Krieger, die den Donauvölkern mit Auszeichnung gedient haben.",
    "pillars.legacy.title": "Vermächtnis",
    "pillars.legacy.text": "Das Haus Habsburg-Lothringen hat über sieben Jahrhunderte Kaiser, Könige und Erzherzöge hervorgebracht. Seit 1917, als Kaiserliches Haus Österreich-Donau, hat es die Donaukonföderation durch die Umwälzungen des zwanzigsten Jahrhunderts und in die Gegenwart geführt.",
    "pillars.link": "Mehr erfahren →",
    // Palace
    "palace.section": "IV · Die Residenz",
    "palace.title": "Palais Danubio",
    "palace.text": "Zwischen 1919 und 1925 am westlichen Donauufer errichtet, dient das Palais Danubio als Sitz des Donaurates — der Versammlung der Gouverneure der sieben Gliedstaaten der Konföderation. Wenn die Gouverneure in Wien zusammenkommen, ist das Palais Danubio ihr offizieller Tagungsort, dessen Großer Ratssaal der Schauplatz der Beratungen ist, die die Föderation regieren.",
    // Timeline
    "timeline.section": "V · Wichtige Daten",
    "timeline.title": "Meilensteine der Dynastie",
    "timeline.1914.event": "Sarajevo: Der Erzherzog überlebt",
    "timeline.1914.desc": "Das Attentat auf Erzherzog Franz Ferdinand in Sarajevo scheitert. Der Erzherzog wird verwundet, überlebt aber. Die europäische Krise wird durch Diplomatie eingedämmt und ein größerer Konflikt abgewendet.",
    "timeline.1917.event": "Vertrag von Wien & die Donauföderation",
    "timeline.1917.desc": "Kaiser Franz Ferdinand I. unterzeichnet den Vertrag von Wien und verwandelt die Österreichisch-Ungarische Monarchie in die Donauföderation von fünfzehn Staaten — eine neue konstitutionelle Ordnung für Mitteleuropa.",
    "timeline.1923.event": "Die Föderationskrone vollendet",
    "timeline.1923.desc": "Die Föderationskrone, 1920 von Kaiser Franz Ferdinand I. in Auftrag gegeben, wird nach drei Jahren Handwerkskunst in Platin, Perlen, Diamanten, Rubinen, Saphiren und Smaragden fertiggestellt.",
    "timeline.1998.event": "Thronbesteigung Maximilians I.",
    "timeline.1998.desc": "Der gegenwärtige Kaiser besteigt den Thron und beginnt eine Regentschaft, die von diplomatischer Erneuerung, kultureller Förderung und der Modernisierung der Institutionen der Konföderation geprägt ist.",
    "timeline.2000.event": "Tragödie im Pariser Ritz",
    "timeline.2000.desc": "Die verstorbene Kaiserin Maria-Cristina kommt bei dem Brand im Pariser Ritz am 10. September ums Leben. Die stoische Trauer des Kaisers und sein fortgesetzter Dienst werden zu einem prägenden Moment seiner Regentschaft.",
    "timeline.2026.event": "Die Kaiserliche Verlobung",
    "timeline.2026.desc": "Kronprinz Leopold von Habsburg und Fräulein Katharina von Richter geben ihre Verlobung bekannt und bringen der Konföderation große Freude.",
    "timeline.link": "Vollständige Geschichte →",
    // Press
    "press.pretitle": "Die Wiener Eleganz · Hofsaison-Sonderbeilage",
    "press.title": "Der Ball, der niemals endet",
    "press.subtitle": "Januar 2026. Zweitausend Gäste. Eine Nacht. Der Hofball kehrt in die Hofburg zurück — und nichts ist mehr wie zuvor.",
    "press.img1": "Der Kaiserliche Cortège · Hofburg, Januar 2026",
    "press.img2": "Über der Hofburg · 360 Drohnen · Januar 2026",
    "press.img3": "Die Bonbonnière · Wiener Werkstätte Neu · 2026",
    "press.link": "Den vollständigen Artikel lesen →",
  },
  en: {
    "nav.home": "Home",
    "nav.history": "History",
    "nav.family": "The Imperial Family",
    "nav.traditions": "Traditions",
    "nav.heraldry": "Heraldry",
    "nav.properties": "Imperial Properties",
    "nav.world": "The World",
    "nav.constitution": "Constitution",
    "nav.books": "The Danubian Throne",
    "nav.press": "Press",
    "header.imperialHouse": "Imperial House",
    "hero.pretitle": "Est. MCMXVII · Neustadt, Danubio",
    "hero.title1": "Imperial House",
    "hero.title2": "of Austria-Danubio",
    "hero.subtitle": "Guardians of the Danube. Heirs of a Thousand Years.",
    "hero.cta1": "Our History",
    "hero.cta2": "The Imperial Family",
    "hero.scroll": "Scroll",
    "announcement": "✦   Imperial Announcement: The engagement of Crown Prince Leopold von Habsburg and Fräulein Katharina von Richter is formally proclaimed — Spring 2026   ✦",
    "about.section": "I · The House",
    "about.title1": "A Dynasty Born",
    "about.title2": "of Eagle and River",
    "about.p1": "The Imperial House of Austria-Danubio is the continuation of the ancient House of Habsburg-Lorraine, one of the most illustrious dynasties in European history. Its roots reach back to the medieval counts of Habsburg and the centuries of Holy Roman Emperors, Kings of Hungary and Bohemia, and Archdukes of Austria. In 1914, the assassination attempt against Archduke Franz Ferdinand in Sarajevo failed — the Archduke survived, and the European crisis that followed was resolved at the negotiating table rather than on the battlefield. The Treaty of Vienna of 1917 transformed the Austro-Hungarian Monarchy into the Danubian Federation: a constitutional confederation of fifteen states united under the Imperial Crown.",
    "about.p2": "Today, under the reign of His Imperial and Royal Apostolic Majesty Emperor Maximilian I — now in his nineteenth year on the throne — the House continues to serve as the constitutional sovereign of the Danubian Confederation, presiding over fifteen states and more than eighty million citizens with dignity, tradition, and an unwavering commitment to the peoples of the river lands.",
    "about.link": "Read the Full History →",
    "emperor.section": "II · The Sovereign",
    "emperor.title": "His Imperial Majesty",
    "emperor.caption": "His Imperial Majesty Maximilian I\nEmperor of Austria-Danubio · 19 years on the throne",
    "emperor.p1": "Born in 1954 at the Hofburg Imperial Palace in Vienna, Maximilian Franz Josef Karl of Austria-Danubio ascended to the Imperial Throne following the passing of his father. He has now reigned for thirty-seven years, presiding over a period of constitutional consolidation and European integration.",
    "emperor.p2": "His Majesty has borne his duties with unwavering dignity in the face of profound personal tragedy. The late Empress Maria-Cristina perished in the fire at the Paris Ritz on the 10th of September, 2000 — a loss that shook the Confederation and the world. He has since devoted himself entirely to his people. The forthcoming marriage of Crown Prince Leopold to Katharina von Richter is a moment of great joy for the Imperial House and the Confederation alike.",
    "emperor.titles.label": "Full Style & Titles",
    "emperor.titles.text": "His Imperial and Royal Majesty Maximilian I, by the Grace of God Emperor of Austria-Danubio, King of the Danubian Lands, Archduke of Neustadt, Grand Duke of the Eastern Marches, Protector of the River Peoples, Knight of the Order of the Golden Eagle.",
    "emperor.link": "Meet the Imperial Family →",
    "pillars.section": "III · Our Foundations",
    "pillars.title": "The Three Pillars of the House",
    "pillars.tradition.title": "Tradition",
    "pillars.tradition.text": "Since 1917, the Imperial House has upheld the ceremonial traditions of the Danubian Confederation — from the annual Feast of the Eagle to the solemn Proclamation of the Emperor from the balcony of the Hofburg and the ancient Hungarian Coronation in Budapest.",
    "pillars.honour.title": "Honour",
    "pillars.honour.text": "The Order of the Golden Eagle, founded in 1917 upon the proclamation of the Danubian Federation, remains the highest honour the Emperor may bestow. Its recipients have included statesmen, scholars, and warriors who have served the Danubian peoples with distinction.",
    "pillars.legacy.title": "Legacy",
    "pillars.legacy.text": "The House of Habsburg-Lorraine has produced emperors, kings, and archdukes across seven centuries. Since 1917, as the Imperial House of Austria-Danubio, it has guided the Danubian Confederation through the upheavals of the twentieth century and into the present age.",
    "pillars.link": "Learn More →",
    "palace.section": "IV · The Residence",
    "palace.title": "Palais Danubio",
    "palace.text": "Constructed between 1919 and 1925 along the western bank of the Danube, the Palais Danubio serves as the seat of the Danubian Council — the assembly of governors of the seven constituent states of the Confederation. When the governors convene in Vienna, the Palais Danubio is their official meeting place, its Grand Council Chamber the setting for the deliberations that govern the Federation.",
    "timeline.section": "V · Key Dates",
    "timeline.title": "Milestones of the Dynasty",
    "timeline.1914.event": "Sarajevo: The Archduke Survives",
    "timeline.1914.desc": "The assassination attempt against Archduke Franz Ferdinand in Sarajevo fails. The Archduke is wounded but survives. The European crisis is contained through diplomacy, averting a wider conflict.",
    "timeline.1917.event": "Treaty of Vienna & the Danubian Federation",
    "timeline.1917.desc": "Emperor Franz Ferdinand I signs the Treaty of Vienna, transforming the Austro-Hungarian Monarchy into the Danubian Federation of fifteen states — a new constitutional order for Central Europe.",
    "timeline.1923.event": "The Federation Crown Completed",
    "timeline.1923.desc": "The Federation Crown, commissioned by Emperor Franz Ferdinand I in 1920, is completed after three years of craftsmanship in platinum, pearls, diamonds, rubies, sapphires, and emeralds.",
    "timeline.1998.event": "Accession of Maximilian I",
    "timeline.1998.desc": "The current Emperor ascends to the throne, beginning a reign marked by diplomatic renewal, cultural patronage, and the modernisation of the Confederation's institutions.",
    "timeline.2000.event": "Tragedy at the Paris Ritz",
    "timeline.2000.desc": "The late Empress Maria-Cristina perishes in the fire at the Paris Ritz on 10 September. The Emperor's stoic grief and continued service become a defining moment of his reign.",
    "timeline.2026.event": "The Imperial Engagement",
    "timeline.2026.desc": "Crown Prince Leopold von Habsburg and Fräulein Katharina von Richter announce their engagement, bringing great joy to the Confederation.",
    "timeline.link": "Full History →",
    "press.pretitle": "Die Wiener Eleganz · Court Season Special",
    "press.title": "The Ball That Never Ends",
    "press.subtitle": "January 2026. Two thousand guests. One night. The Court Ball returns to the Hofburg — and nothing is quite as it was.",
    "press.img1": "The Imperial Cortège · Hofburg, January 2026",
    "press.img2": "Above the Hofburg · 360 Drones · January 2026",
    "press.img3": "The Bonbonnière · Wiener Werkstätte Neu · 2026",
    "press.link": "Read the Full Article →",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.history": "Histoire",
    "nav.family": "La Famille Impériale",
    "nav.traditions": "Traditions",
    "nav.heraldry": "Héraldique",
    "nav.properties": "Résidences Impériales",
    "nav.world": "Le Monde",
    "nav.constitution": "Constitution",
    "nav.books": "Le Trône Danubien",
    "nav.press": "Presse",
    "header.imperialHouse": "Maison Impériale",
    "hero.pretitle": "Fond. MCMXVII · Neustadt, Danube",
    "hero.title1": "Maison Impériale",
    "hero.title2": "d'Autriche-Danube",
    "hero.subtitle": "Gardiens du Danube. Héritiers d'un millénaire.",
    "hero.cta1": "Notre Histoire",
    "hero.cta2": "La Famille Impériale",
    "hero.scroll": "Défiler",
    "announcement": "✦   Annonce Impériale : Les fiançailles du Prince Héritier Léopold von Habsburg et de Mademoiselle Katharina von Richter sont officiellement proclamées — Printemps 2026   ✦",
    "about.section": "I · La Maison",
    "about.title1": "Une Dynastie née",
    "about.title2": "de l'Aigle et du Fleuve",
    "about.p1": "La Maison Impériale d'Autriche-Danube est la continuation de l'ancienne Maison de Habsbourg-Lorraine, l'une des dynasties les plus illustres de l'histoire européenne. Ses racines remontent aux comtes médiévaux de Habsbourg et aux siècles d'Empereurs du Saint-Empire, de Rois de Hongrie et de Bohême, et d'Archiducs d'Autriche. En 1914, la tentative d'assassinat contre l'Archiduc François-Ferdinand à Sarajevo échoua — l'Archiduc survécut, et la crise européenne fut résolue à la table des négociations plutôt que sur le champ de bataille. Le Traité de Vienne de 1917 transforma la Monarchie austro-hongroise en la Fédération Danubienne.",
    "about.p2": "Aujourd'hui, sous le règne de Sa Majesté Impériale et Royale Apostolique l'Empereur Maximilien Ier — désormais dans sa dix-neuvième année de règne — la Maison continue de servir en tant que souverain constitutionnel de la Confédération Danubienne, présidant sur quinze États et plus de quatre-vingts millions de citoyens avec dignité, tradition et un engagement indéfectible envers les peuples des terres fluviales.",
    "about.link": "Lire l'histoire complète →",
    "emperor.section": "II · Le Souverain",
    "emperor.title": "Sa Majesté Impériale",
    "emperor.link": "Rencontrer la Famille Impériale →",
    "pillars.section": "III · Nos Fondements",
    "pillars.title": "Les Trois Piliers de la Maison",
    "pillars.tradition.title": "Tradition",
    "pillars.honour.title": "Honneur",
    "pillars.legacy.title": "Héritage",
    "pillars.link": "En savoir plus →",
    "palace.section": "IV · La Résidence",
    "palace.title": "Palais Danubio",
    "timeline.section": "V · Dates Clés",
    "timeline.title": "Jalons de la Dynastie",
    "timeline.link": "Histoire complète →",
    "press.title": "Le Bal qui ne finit jamais",
    "press.link": "Lire l'article complet →",
  },
  hu: {
    "nav.home": "Kezdőlap",
    "nav.history": "Történelem",
    "nav.family": "A Császári Család",
    "nav.traditions": "Hagyományok",
    "nav.heraldry": "Heraldika",
    "nav.properties": "Császári Rezidenciák",
    "nav.world": "A Világ",
    "nav.constitution": "Alkotmány",
    "nav.books": "A Dunai Trón",
    "nav.press": "Sajtó",
    "header.imperialHouse": "Császári Ház",
    "hero.pretitle": "Alapítva MCMXVII · Neustadt, Duna",
    "hero.title1": "Császári Ház",
    "hero.title2": "Ausztria-Duna",
    "hero.subtitle": "A Duna őrzői. Ezer év örökösei.",
    "hero.cta1": "Történelmünk",
    "hero.cta2": "A Császári Család",
    "hero.scroll": "Görgetés",
    "about.section": "I · A Ház",
    "about.title1": "Egy dinasztia született",
    "about.title2": "Sasból és Folyóból",
    "about.link": "A teljes történelem →",
    "emperor.section": "II · Az Uralkodó",
    "emperor.title": "Őfelsége a Császár",
    "emperor.link": "A Császári Család →",
    "pillars.section": "III · Alapjaink",
    "pillars.title": "A Ház Három Pillére",
    "pillars.tradition.title": "Hagyomány",
    "pillars.honour.title": "Becsület",
    "pillars.legacy.title": "Örökség",
    "pillars.link": "Tovább →",
    "palace.section": "IV · A Rezidencia",
    "timeline.section": "V · Fontos Dátumok",
    "timeline.title": "A Dinasztia Mérföldkövei",
    "timeline.link": "Teljes történelem →",
    "press.title": "A Bál, amely soha nem ér véget",
    "press.link": "A teljes cikk →",
  },
  cs: {
    "nav.home": "Úvod",
    "nav.history": "Historie",
    "nav.family": "Císařská Rodina",
    "nav.traditions": "Tradice",
    "nav.heraldry": "Heraldika",
    "nav.properties": "Císařské Rezidence",
    "nav.world": "Svět",
    "nav.constitution": "Ústava",
    "nav.books": "Dunajský Trůn",
    "nav.press": "Tisk",
    "header.imperialHouse": "Císařský Dům",
    "hero.pretitle": "Zal. MCMXVII · Neustadt, Dunaj",
    "hero.title1": "Císařský Dům",
    "hero.title2": "Rakousko-Dunaj",
    "hero.subtitle": "Strážci Dunaje. Dědicové tisíciletí.",
    "hero.cta1": "Naše Historie",
    "hero.cta2": "Císařská Rodina",
    "hero.scroll": "Posuňte",
    "about.section": "I · Dům",
    "about.title1": "Dynastie zrozená",
    "about.title2": "z Orla a Řeky",
    "about.link": "Celá historie →",
    "emperor.section": "II · Panovník",
    "emperor.title": "Jeho Císařské Veličenstvo",
    "emperor.link": "Císařská Rodina →",
    "pillars.section": "III · Naše Základy",
    "pillars.title": "Tři Pilíře Domu",
    "pillars.tradition.title": "Tradice",
    "pillars.honour.title": "Čest",
    "pillars.legacy.title": "Odkaz",
    "pillars.link": "Více →",
    "palace.section": "IV · Rezidence",
    "timeline.section": "V · Klíčová Data",
    "timeline.title": "Milníky Dynastie",
    "timeline.link": "Celá historie →",
    "press.title": "Ples, který nikdy nekončí",
    "press.link": "Celý článek →",
  },
  hr: {
    "nav.home": "Početna",
    "nav.history": "Povijest",
    "nav.family": "Carska Obitelj",
    "nav.traditions": "Tradicije",
    "nav.heraldry": "Heraldika",
    "nav.properties": "Carske Rezidencije",
    "nav.world": "Svijet",
    "nav.constitution": "Ustav",
    "nav.books": "Dunavski Prijestolje",
    "nav.press": "Tisak",
    "header.imperialHouse": "Carski Dom",
    "hero.pretitle": "Osn. MCMXVII · Neustadt, Dunav",
    "hero.title1": "Carski Dom",
    "hero.title2": "Austrija-Dunav",
    "hero.subtitle": "Čuvari Dunava. Nasljednici tisućljeća.",
    "hero.cta1": "Naša Povijest",
    "hero.cta2": "Carska Obitelj",
    "hero.scroll": "Pomicanje",
    "about.section": "I · Dom",
    "about.title1": "Dinastija rođena",
    "about.title2": "od Orla i Rijeke",
    "about.link": "Cijela povijest →",
    "emperor.section": "II · Vladar",
    "emperor.title": "Njegovo Carsko Veličanstvo",
    "emperor.link": "Carska Obitelj →",
    "pillars.section": "III · Naši Temelji",
    "pillars.title": "Tri Stupa Doma",
    "pillars.tradition.title": "Tradicija",
    "pillars.honour.title": "Čast",
    "pillars.legacy.title": "Naslijeđe",
    "pillars.link": "Više →",
    "palace.section": "IV · Rezidencija",
    "timeline.section": "V · Ključni Datumi",
    "timeline.title": "Prekretnice Dinastije",
    "timeline.link": "Cijela povijest →",
    "press.title": "Bal koji nikada ne završava",
    "press.link": "Cijeli članak →",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("df-language");
    return (saved as Language) || "de";
  });

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("df-language", lang);
  }, []);

  const t = useCallback(
    (key: string): string => {
      // Try current language, fallback to German, then English, then key
      return translations[language]?.[key] || translations.de[key] || translations.en[key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
