/**
 * Language Context — Multilingual support for the Danubian Federation website
 * Default: German (de), with English, French, Hungarian, Czech, Croatian
 */
import { createContext, useContext, useState, useCallback, useMemo, type ReactNode } from "react";
import { historyTranslations, familyTranslations, worldTranslations, constitutionTranslations, booksTranslations, footerTranslations, transparencyTranslations, pressTranslations, newsTranslations, traditionsTranslations, heraldryTranslations, propertiesTranslations } from "@/i18n";

export type Language = "de" | "en" | "fr" | "hu" | "cs" | "hr" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  switching: boolean;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

// Translation dictionary — Home page (Option B: only Home translated for now)
const translations: Record<Language, Record<string, string>> = {
  de: {
    // Nav
    "nav.home": "Startseite",
    "nav.history": "Geschichte",
    "nav.family": "Die Kaiserliche Familie",
    "nav.traditions": "Traditionen",
    "nav.heraldry": "Heraldik",
    "nav.properties": "Kaiserliche Residenzen",
    "nav.world": "Die Welt",
    "nav.constitution": "Verfassung",
    "nav.books": "Der Donau-Thron",
    "nav.press": "Presse",
    "nav.transparency": "Transparenz",
    "nav.news": "Nachrichten",
    // Header
    "header.imperialHouse": "Kaiserliches Haus",
    // Hero
    "hero.pretitle": "Gegr. MCMXVII · Neustadt, Donau",
    "hero.title1": "Kaiserliches Haus",
    "hero.title2": "Österreich-Donau",
    "hero.subtitle": "Hüter der Donau. Erben eines Jahrtausends.",
    "hero.cta1": "Unsere Geschichte",
    "hero.cta2": "Die Kaiserliche Familie",
    "hero.scroll": "Scrollen",
    // Announcement
    "announcement": "✦   Kaiserliche Bekanntmachung: Die Verlobung von Kronprinz Leopold von Habsburg und Fräulein Katharina von Richter wird hiermit feierlich verkündet — Frühling 2026   ✦",
    // About
    "about.section": "I · Das Haus",
    "about.title1": "Eine Dynastie geboren",
    "about.title2": "aus Adler und Fluss",
    "about.p1": "Das Kaiserliche Haus Österreich-Donau ist die Fortführung des altehrwürdigen Hauses Habsburg-Lothringen, einer der erhabensten Dynastien der europäischen Geschichte. Seine Wurzeln reichen zurück zu den mittelalterlichen Grafen von Habsburg und den Jahrhunderten der Kaiser des Heiligen Römischen Reiches, Könige von Ungarn und Böhmen und Erzherzöge von Österreich. Im Jahr 1914 scheiterte das Attentat auf Erzherzog Franz Ferdinand in Sarajevo — der Erzherzog überlebte, und die europäische Krise wurde am Verhandlungstisch gelöst, nicht auf dem Schlachtfeld. Der Vertrag von Wien von 1917 verwandelte die Österreichisch-Ungarische Monarchie in die Donauföderation: eine konstitutionelle Konföderation von vierzehn Gliedstaaten, zwei assoziierten Königreichen und einem Protektorat, vereint unter der Kaiserkrone.",
    "about.p2": "Heute, unter der Regentschaft Seiner Kaiserlichen und Königlichen Apostolischen Majestät Kaiser Maximilian II. — nun im siebenunddreißigsten Jahr auf dem Thron — dient das Haus weiterhin als konstitutioneller Souverän der Donaukonföderation und regiert über vierzehn Gliedstaaten, zwei assoziierte Königreiche und mehr als achtzig Millionen Bürger mit Würde, Tradition und unerschütterlichem Engagement für die Völker der Flussländer.",
    "about.link": "Die vollständige Geschichte lesen →",
    // Emperor
    "emperor.section": "II · Der Souverän",
    "emperor.title": "Seine Kaiserliche Majestät",
    "emperor.caption": "Seine Kaiserliche Majestät Maximilian II.\nKaiser von Österreich-Donau · 37 Jahre auf dem Thron",
    "emperor.p1": "Geboren 1954 in der Hofburg in Wien, bestieg Maximilian Franz Josef Karl von Österreich-Donau den Kaiserthron nach dem Ableben seines Vaters. Er regiert nun seit siebenunddreißig Jahren und präsidiert über eine Epoche der konstitutionellen Konsolidierung und europäischen Integration.",
    "emperor.p2": "Seine Majestät hat seine Pflichten mit unerschütterlicher Würde angesichts tiefgreifender persönlicher Tragödie getragen. Die verstorbene Kaiserin Maria-Cristina kam bei dem Brand im Pariser Ritz am 10. September 2000 ums Leben — ein Verlust, der die Konföderation und die Welt erschütterte. Seither hat er sich ganz seinem Volk gewidmet. Die bevorstehende Vermählung von Kronprinz Leopold mit Katharina von Richter ist ein Moment großer Freude für das Kaiserliche Haus und die Konföderation gleichermaßen.",
    "emperor.titles.label": "Vollständiger Stil & Titel",
    "emperor.titles.text": "Seine Kaiserliche und Königliche Majestät Maximilian II., von Gottes Gnaden Kaiser von Österreich-Donau, König der Donauländer, Erzherzog von Neustadt, Großherzog der Ostmarken, Beschützer der Flussvölker, Ritter des Ordens vom Goldenen Adler.",
    "emperor.link": "Die Kaiserliche Familie kennenlernen →",
    // Pillars
    "pillars.section": "III · Unsere Grundlagen",
    "pillars.title": "Die drei Säulen des Hauses",
    "pillars.tradition.title": "Tradition",
    "pillars.tradition.text": "Seit 1917 pflegt das Kaiserliche Haus die zeremoniellen Traditionen der Donaukonföderation — vom jährlichen Fest des Adlers bis zur feierlichen Proklamation des Kaisers vom Balkon der Hofburg und der altehrwürdigen ungarischen Krönung in Budapest.",
    "pillars.honour.title": "Ehre",
    "pillars.honour.text": "Der Orden vom Goldenen Adler, gegründet 1917 bei der Proklamation der Donauföderation, bleibt die höchste Auszeichnung, die der Kaiser verleihen kann. Zu seinen Trägern zählen Staatsmänner, Gelehrte und Krieger, die den Donauvölkern mit Auszeichnung gedient haben.",
    "pillars.legacy.title": "Vermächtnis",
    "pillars.legacy.text": "Das Haus Habsburg-Lothringen hat über sieben Jahrhunderte Kaiser, Könige und Erzherzöge hervorgebracht. Seit 1917, als Kaiserliches Haus Österreich-Donau, hat es die Donaukonföderation durch die Umwälzungen des zwanzigsten Jahrhunderts und in die Gegenwart geführt.",
    "pillars.link": "Mehr erfahren →",
    // Palace
    "palace.section": "IV · Die Residenz",
    "palace.title": "Palais Danubio",
    "palace.text": "Zwischen 1919 und 1925 am westlichen Donauufer errichtet, dient das Palais Danubio als Sitz des Donaurates — der Versammlung der Gouverneure der sieben Gliedstaaten der Konföderation. Wenn die Gouverneure in Wien zusammenkommen, ist das Palais Danubio ihr offizieller Tagungsort, dessen Großer Ratssaal der Schauplatz der Beratungen ist, die die Föderation regieren.",
    // Timeline
    "timeline.section": "V · Wichtige Daten",
    "timeline.title": "Meilensteine der Dynastie",
    "timeline.1914.event": "Sarajevo: Der Erzherzog überlebt",
    "timeline.1914.desc": "Das Attentat auf Erzherzog Franz Ferdinand in Sarajevo scheitert. Der Erzherzog wird verwundet, überlebt aber. Die europäische Krise wird durch Diplomatie eingedämmt und ein größerer Konflikt abgewendet.",
    "timeline.1917.event": "Vertrag von Wien & die Donauföderation",
    "timeline.1917.desc": "Kaiser Franz Ferdinand I. unterzeichnet den Vertrag von Wien und verwandelt die Österreichisch-Ungarische Monarchie in die Donauföderation von vierzehn Gliedstaaten mit assoziierten Königreichen — eine neue konstitutionelle Ordnung für Mitteleuropa.",
    "timeline.1923.event": "Die Föderationskrone vollendet",
    "timeline.1923.desc": "Die Föderationskrone, 1920 von Kaiser Franz Ferdinand I. in Auftrag gegeben, wird nach drei Jahren Handwerkskunst in Platin, Perlen, Diamanten, Rubinen, Saphiren und Smaragden fertiggestellt.",
    "timeline.1998.event": "Thronbesteigung Maximilians II.",
    "timeline.1998.desc": "Der gegenwärtige Kaiser besteigt den Thron und beginnt eine Regentschaft, die von diplomatischer Erneuerung, kultureller Förderung und der Modernisierung der Institutionen der Konföderation geprägt ist.",
    "timeline.2000.event": "Tragödie im Pariser Ritz",
    "timeline.2000.desc": "Die verstorbene Kaiserin Maria-Cristina kommt bei dem Brand im Pariser Ritz am 10. September ums Leben. Die stoische Trauer des Kaisers und sein fortgesetzter Dienst werden zu einem prägenden Moment seiner Regentschaft.",
    "timeline.2026.event": "Die Kaiserliche Verlobung",
    "timeline.2026.desc": "Kronprinz Leopold von Habsburg und Fräulein Katharina von Richter geben ihre Verlobung bekannt und bringen der Konföderation große Freude.",
    "timeline.link": "Vollständige Geschichte →",
    // Press
    "press.pretitle": "Die Wiener Eleganz · Hofsaison-Sonderbeilage",
    "press.title": "Der Ball, der niemals endet",
    "press.subtitle": "Januar 2026. Zweitausend Gäste. Eine Nacht. Der Hofball kehrt in die Hofburg zurück — und nichts ist mehr wie zuvor.",
    "press.img1": "Der Kaiserliche Cortège · Hofburg, Januar 2026",
    "press.img2": "Über der Hofburg · 360 Drohnen · Januar 2026",
    "press.img3": "Die Bonbonnière · Wiener Werkstätte Neu · 2026",
    "press.link": "Den vollständigen Artikel lesen →",
  },
  en: {
    "nav.home": "Home",
    "nav.history": "History",
    "nav.family": "The Imperial Family",
    "nav.traditions": "Traditions",
    "nav.heraldry": "Heraldry",
    "nav.properties": "Imperial Properties",
    "nav.world": "The World",
    "nav.constitution": "Constitution",
    "nav.books": "The Danubian Throne",
    "nav.press": "Press",
    "nav.transparency": "Transparency",
    "nav.news": "News",
    "header.imperialHouse": "Imperial House",
    "hero.pretitle": "Est. MCMXVII · Neustadt, Danubio",
    "hero.title1": "Imperial House",
    "hero.title2": "of Austria-Danubio",
    "hero.subtitle": "Guardians of the Danube. Heirs of a Thousand Years.",
    "hero.cta1": "Our History",
    "hero.cta2": "The Imperial Family",
    "hero.scroll": "Scroll",
    "announcement": "✦   Imperial Announcement: The engagement of Crown Prince Leopold von Habsburg and Fräulein Katharina von Richter is formally proclaimed — Spring 2026   ✦",
    "about.section": "I · The House",
    "about.title1": "A Dynasty Born",
    "about.title2": "of Eagle and River",
    "about.p1": "The Imperial House of Austria-Danubio is the continuation of the ancient House of Habsburg-Lorraine, one of the most illustrious dynasties in European history. Its roots reach back to the medieval counts of Habsburg and the centuries of Holy Roman Emperors, Kings of Hungary and Bohemia, and Archdukes of Austria. In 1914, the assassination attempt against Archduke Franz Ferdinand in Sarajevo failed — the Archduke survived, and the European crisis that followed was resolved at the negotiating table rather than on the battlefield. The Treaty of Vienna of 1917 transformed the Austro-Hungarian Monarchy into the Danubian Federation: a constitutional confederation of fourteen constituent states, two associated kingdoms, and one protectorate, united under the Imperial Crown.",
    "about.p2": "Today, under the reign of His Imperial and Royal Apostolic Majesty Emperor Maximilian II — now in his thirty-seventh year on the throne — the House continues to serve as the constitutional sovereign of the Danubian Confederation, presiding over fourteen constituent states, two associated kingdoms, and more than eighty million citizens with dignity, tradition, and an unwavering commitment to the peoples of the river lands.",
    "about.link": "Read the Full History →",
    "emperor.section": "II · The Sovereign",
    "emperor.title": "His Imperial Majesty",
    "emperor.caption": "His Imperial Majesty Maximilian II\nEmperor of Austria-Danubio · 37 years on the throne",
    "emperor.p1": "Born in 1954 at the Hofburg Imperial Palace in Vienna, Maximilian Franz Josef Karl of Austria-Danubio ascended to the Imperial Throne following the passing of his father. He has now reigned for thirty-seven years, presiding over a period of constitutional consolidation and European integration.",
    "emperor.p2": "His Majesty has borne his duties with unwavering dignity in the face of profound personal tragedy. The late Empress Maria-Cristina perished in the fire at the Paris Ritz on the 10th of September, 2000 — a loss that shook the Confederation and the world. He has since devoted himself entirely to his people. The forthcoming marriage of Crown Prince Leopold to Katharina von Richter is a moment of great joy for the Imperial House and the Confederation alike.",
    "emperor.titles.label": "Full Style & Titles",
    "emperor.titles.text": "His Imperial and Royal Majesty Maximilian II, by the Grace of God Emperor of Austria-Danubio, King of the Danubian Lands, Archduke of Neustadt, Grand Duke of the Eastern Marches, Protector of the River Peoples, Knight of the Order of the Golden Eagle.",
    "emperor.link": "Meet the Imperial Family →",
    "pillars.section": "III · Our Foundations",
    "pillars.title": "The Three Pillars of the House",
    "pillars.tradition.title": "Tradition",
    "pillars.tradition.text": "Since 1917, the Imperial House has upheld the ceremonial traditions of the Danubian Confederation — from the annual Feast of the Eagle to the solemn Proclamation of the Emperor from the balcony of the Hofburg and the ancient Hungarian Coronation in Budapest.",
    "pillars.honour.title": "Honour",
    "pillars.honour.text": "The Order of the Golden Eagle, founded in 1917 upon the proclamation of the Danubian Federation, remains the highest honour the Emperor may bestow. Its recipients have included statesmen, scholars, and warriors who have served the Danubian peoples with distinction.",
    "pillars.legacy.title": "Legacy",
    "pillars.legacy.text": "The House of Habsburg-Lorraine has produced emperors, kings, and archdukes across seven centuries. Since 1917, as the Imperial House of Austria-Danubio, it has guided the Danubian Confederation through the upheavals of the twentieth century and into the present age.",
    "pillars.link": "Learn More →",
    "palace.section": "IV · The Residence",
    "palace.title": "Palais Danubio",
    "palace.text": "Constructed between 1919 and 1925 along the western bank of the Danube, the Palais Danubio serves as the seat of the Danubian Council — the assembly of governors of the seven constituent states of the Confederation. When the governors convene in Vienna, the Palais Danubio is their official meeting place, its Grand Council Chamber the setting for the deliberations that govern the Federation.",
    "timeline.section": "V · Key Dates",
    "timeline.title": "Milestones of the Dynasty",
    "timeline.1914.event": "Sarajevo: The Archduke Survives",
    "timeline.1914.desc": "The assassination attempt against Archduke Franz Ferdinand in Sarajevo fails. The Archduke is wounded but survives. The European crisis is contained through diplomacy, averting a wider conflict.",
    "timeline.1917.event": "Treaty of Vienna & the Danubian Federation",
    "timeline.1917.desc": "Emperor Franz Ferdinand I signs the Treaty of Vienna, transforming the Austro-Hungarian Monarchy into the Danubian Federation of fourteen constituent states with associated kingdoms — a new constitutional order for Central Europe.",
    "timeline.1923.event": "The Federation Crown Completed",
    "timeline.1923.desc": "The Federation Crown, commissioned by Emperor Franz Ferdinand I in 1920, is completed after three years of craftsmanship in platinum, pearls, diamonds, rubies, sapphires, and emeralds.",
    "timeline.1998.event": "Accession of Maximilian II",
    "timeline.1998.desc": "The current Emperor ascends to the throne, beginning a reign marked by diplomatic renewal, cultural patronage, and the modernisation of the Confederation's institutions.",
    "timeline.2000.event": "Tragedy at the Paris Ritz",
    "timeline.2000.desc": "The late Empress Maria-Cristina perishes in the fire at the Paris Ritz on 10 September. The Emperor's stoic grief and continued service become a defining moment of his reign.",
    "timeline.2026.event": "The Imperial Engagement",
    "timeline.2026.desc": "Crown Prince Leopold von Habsburg and Fräulein Katharina von Richter announce their engagement, bringing great joy to the Confederation.",
    "timeline.link": "Full History →",
    "press.pretitle": "Die Wiener Eleganz · Court Season Special",
    "press.title": "The Ball That Never Ends",
    "press.subtitle": "January 2026. Two thousand guests. One night. The Court Ball returns to the Hofburg — and nothing is quite as it was.",
    "press.img1": "The Imperial Cortège · Hofburg, January 2026",
    "press.img2": "Above the Hofburg · 360 Drones · January 2026",
    "press.img3": "The Bonbonnière · Wiener Werkstätte Neu · 2026",
    "press.link": "Read the Full Article →",
  },
  fr: {
    "nav.home": "Accueil",
    "nav.history": "Histoire",
    "nav.family": "La Famille Impériale",
    "nav.traditions": "Traditions",
    "nav.heraldry": "Héraldique",
    "nav.properties": "Résidences Impériales",
    "nav.world": "Le Monde",
    "nav.constitution": "Constitution",
    "nav.books": "Le Trône Danubien",
    "nav.press": "Presse",
    "nav.transparency": "Transparence",
    "nav.news": "Nouvelles",
    "header.imperialHouse": "Maison Impériale",
    "hero.pretitle": "Fond. MCMXVII · Neustadt, Danube",
    "hero.title1": "Maison Impériale",
    "hero.title2": "d'Autriche-Danube",
    "hero.subtitle": "Gardiens du Danube. Héritiers d'un millénaire.",
    "hero.cta1": "Notre Histoire",
    "hero.cta2": "La Famille Impériale",
    "hero.scroll": "Défiler",
    "announcement": "✦   Annonce Impériale : Les fiançailles du Prince Héritier Léopold von Habsburg et de Mademoiselle Katharina von Richter sont officiellement proclamées — Printemps 2026   ✦",
    "about.section": "I · La Maison",
    "about.title1": "Une Dynastie née",
    "about.title2": "de l'Aigle et du Fleuve",
    "about.p1": "La Maison Impériale d'Autriche-Danube est la continuation de l'ancienne Maison de Habsbourg-Lorraine, l'une des dynasties les plus illustres de l'histoire européenne. Ses racines remontent aux comtes médiévaux de Habsbourg et aux siècles d'Empereurs du Saint-Empire, de Rois de Hongrie et de Bohême, et d'Archiducs d'Autriche. En 1914, la tentative d'assassinat contre l'Archiduc François-Ferdinand à Sarajevo échoua — l'Archiduc survécut, et la crise européenne fut résolue à la table des négociations plutôt que sur le champ de bataille. Le Traité de Vienne de 1917 transforma la Monarchie austro-hongroise en la Fédération Danubienne.",
    "about.p2": "Aujourd'hui, sous le règne de Sa Majesté Impériale et Royale Apostolique l'Empereur Maximilien II — désormais dans sa trente-septième année de règne — la Maison continue de servir en tant que souverain constitutionnel de la Confédération Danubienne, présidant sur quatorze États constituants, deux royaumes associés et plus de quatre-vingts millions de citoyens avec dignité, tradition et un engagement indéfectible envers les peuples des terres fluviales.",
    "about.link": "Lire l'histoire complète →",
    "emperor.section": "II · Le Souverain",
    "emperor.title": "Sa Majesté Impériale",
    "emperor.link": "Rencontrer la Famille Impériale →",
    "pillars.section": "III · Nos Fondements",
    "pillars.title": "Les Trois Piliers de la Maison",
    "pillars.tradition.title": "Tradition",
    "pillars.honour.title": "Honneur",
    "pillars.legacy.title": "Héritage",
    "pillars.link": "En savoir plus →",
    "palace.section": "IV · La Résidence",
    "palace.title": "Palais Danubio",
    "timeline.section": "V · Dates Clés",
    "timeline.title": "Jalons de la Dynastie",
    "timeline.link": "Histoire complète →",
    "press.title": "Le Bal qui ne finit jamais",
    "press.link": "Lire l'article complet →",
    "emperor.caption": "Sa Majesté Impériale Maximilien II\nEmpereur d'Autriche-Danube · 37 ans de règne",
    "emperor.p1": "Né en 1954 au palais impérial de la Hofburg à Vienne, Maximilien Franz Josef Karl d'Autriche-Danube accéda au Trône Impérial après le décès de son père. Il règne depuis trente-sept ans, présidant une période de consolidation constitutionnelle et d'intégration européenne.",
    "emperor.p2": "Sa Majesté a porté ses devoirs avec une dignité inébranlable face à une profonde tragédie personnelle. La défunte Impératrice Maria-Cristina périt dans l'incendie du Ritz parisien le 10 septembre 2000 — une perte qui ébranla la Confédération et le monde. Le prochain mariage du Prince héritier Léopold avec Katharina von Richter est un moment de grande joie pour la Maison Impériale.",
    "emperor.titles.label": "Style & Titres Complets",
    "emperor.titles.text": "Sa Majesté Impériale et Royale Maximilien II, par la Grâce de Dieu Empereur d'Autriche-Danube, Roi des Terres Danubiennes, Archiduc de Neustadt, Grand-Duc des Marches Orientales, Protecteur des Peuples du Fleuve, Chevalier de l'Ordre de l'Aigle d'Or.",
    "pillars.tradition.text": "Depuis 1917, la Maison Impériale perpétue les traditions cérémonielles de la Confédération Danubienne — de la Fête annuelle de l'Aigle à la Proclamation solennelle de l'Empereur depuis le balcon de la Hofburg et l'ancien Couronnement hongrois à Budapest.",
    "pillars.honour.text": "L'Ordre de l'Aigle d'Or, fondé en 1917 lors de la proclamation de la Fédération Danubienne, demeure la plus haute distinction que l'Empereur puisse conférer.",
    "pillars.legacy.text": "La Maison de Habsbourg-Lorraine a produit des empereurs, des rois et des archiducs pendant sept siècles. Depuis 1917, en tant que Maison Impériale d'Autriche-Danube, elle a guidé la Confédération Danubienne à travers les bouleversements du vingtième siècle.",
    "palace.text": "Construit entre 1919 et 1925 le long de la rive occidentale du Danube, le Palais Danubio sert de siège au Conseil Danubien — l'assemblée des gouverneurs des sept États constituants de la Confédération.",
    "timeline.1914.event": "Sarajevo : L'Archiduc Survit",
    "timeline.1914.desc": "La tentative d'assassinat contre l'Archiduc François-Ferdinand à Sarajevo échoue. L'Archiduc est blessé mais survit. La crise européenne est contenue par la diplomatie.",
    "timeline.1917.event": "Traité de Vienne & la Fédération Danubienne",
    "timeline.1917.desc": "L'Empereur François-Ferdinand Ier signe le Traité de Vienne, transformant la Monarchie austro-hongroise en la Fédération Danubienne de quatorze États constituants avec des royaumes associés.",
    "timeline.1923.event": "La Couronne de la Fédération Achevée",
    "timeline.1923.desc": "La Couronne de la Fédération, commandée par l'Empereur François-Ferdinand Ier en 1920, est achevée après trois ans d'artisanat en platine, perles, diamants, rubis, saphirs et émeraudes.",
    "timeline.1998.event": "Accession de Maximilien II",
    "timeline.1998.desc": "L'Empereur actuel monte sur le trône, commençant un règne marqué par le renouveau diplomatique, le mécénat culturel et la modernisation des institutions.",
    "timeline.2000.event": "Tragédie au Ritz Parisien",
    "timeline.2000.desc": "La défunte Impératrice Maria-Cristina périt dans l'incendie du Ritz parisien le 10 septembre. Le deuil stoïque de l'Empereur devient un moment déterminant de son règne.",
    "timeline.2026.event": "Les Fiançailles Impériales",
    "timeline.2026.desc": "Le Prince héritier Léopold von Habsburg et Mademoiselle Katharina von Richter annoncent leurs fiançailles, apportant une grande joie à la Confédération.",
    "press.pretitle": "Die Wiener Eleganz · Supplément Spécial Saison de la Cour",
    "press.subtitle": "Janvier 2026. Deux mille invités. Une nuit. Le Bal de la Cour revient à la Hofburg — et rien n'est plus comme avant.",
    "press.img1": "Le Cortège Impérial · Hofburg, Janvier 2026",
    "press.img2": "Au-dessus de la Hofburg · 360 Drones · Janvier 2026",
    "press.img3": "La Bonbonnière · Wiener Werkstätte Neu · 2026",
  },
  hu: {
    "nav.home": "Kezdőlap",
    "nav.history": "Történelem",
    "nav.family": "A Császári Család",
    "nav.traditions": "Hagyományok",
    "nav.heraldry": "Heraldika",
    "nav.properties": "Császári Rezidenciák",
    "nav.world": "A Világ",
    "nav.constitution": "Alkotmány",
    "nav.books": "A Dunai Trón",
    "nav.press": "Sajtó",
    "nav.transparency": "Átláthatóság",
    "nav.news": "Hírek",
    "header.imperialHouse": "Császári Ház",
    "hero.pretitle": "Alapítva MCMXVII · Neustadt, Duna",
    "hero.title1": "Császári Ház",
    "hero.title2": "Ausztria-Duna",
    "hero.subtitle": "A Duna őrzői. Ezer év örökösei.",
    "hero.cta1": "Történelmünk",
    "hero.cta2": "A Császári Család",
    "hero.scroll": "Görgetés",
    "about.section": "I · A Ház",
    "about.title1": "Egy dinasztia született",
    "about.title2": "Sasból és Folyóból",
    "about.link": "A teljes történelem →",
    "emperor.section": "II · Az Uralkodó",
    "emperor.title": "Őfelsége a Császár",
    "emperor.link": "A Császári Család →",
    "pillars.section": "III · Alapjaink",
    "pillars.title": "A Ház Három Pillére",
    "pillars.tradition.title": "Hagyomány",
    "pillars.honour.title": "Becsület",
    "pillars.legacy.title": "Örökség",
    "pillars.link": "Tovább →",
    "palace.section": "IV · A Rezidencia",
    "timeline.section": "V · Fontos Dátumok",
    "timeline.title": "A Dinasztia Mérföldkövei",
    "timeline.link": "Teljes történelem →",
    "press.title": "A Bál, amely soha nem ér véget",
    "press.link": "A teljes cikk →",
    "announcement": "✦   Császári Közlemény: Leopold von Habsburg koronaherceg és Katharina von Richter kisasszony eljegyzése ezennel ünnepélyesen kihirdettetik — 2026 tavasza   ✦",
    "about.p1": "Az Ausztria-Duna Császári Ház az ősi Habsburg-Lotaringiai Ház folytatása, az európai történelem egyik legdicsőbb dinasztiája. Gyökerei a középkori Habsburg grófokig és a Német-római Birodalom császárainak, Magyarország és Csehország királyainak, valamint Ausztria főhercegeinek évszázadaiig nyúlnak vissza. 1914-ben a Ferenc Ferdinánd főherceg elleni merénylet Szarajevóban kudarcot vallott — a főherceg túlélte, és az európai válságot a tárgyalóasztalnál oldották meg, nem a csatatéren. Az 1917-es bécsi szerződés az Osztrák-Magyar Monarchiát Dunai Föderációvá alakította: tizennégy tagállam, két társult királyság és egy protektorátus alkotmányos konföderációjává, amelyet a Császári Korona egyesít.",
    "about.p2": "Ma, Őcsászári és Királyi Apostoli Felsége II. Miksa császár uralkodása alatt — immár harminchetedik éve a trónon — a Ház továbbra is a Dunai Konföderáció alkotmányos szuverénje, tizennégy tagállam, két társult királyság és több mint nyolcvanmillió polgár felett elnökölve méltósággal, hagyománnyal és rendíthetetlen elkötelezettséggel a folyóvidéki népek iránt.",
    "emperor.caption": "Őcsászári Felsége II. Miksa\nAusztria-Duna Császára · 37 éve a trónon",
    "emperor.p1": "1954-ben született a bécsi Hofburg Császári Palotában. Ausztria-Duna Miksa Ferenc József Károly apja halálát követően lépett a Császári Trónra. Immár harminchat éve uralkodik, az alkotmányos konszolidáció és az európai integráció korszakát vezetve.",
    "emperor.p2": "Őfelsége rendíthetetlen méltósággal viselte kötelességeit mély személyes tragédiával szemben. A néhai Mária-Krisztina császárné a párizsi Ritz szálloda tűzvészében vesztette életét 2000. szeptember 10-én — egy veszteség, amely megrázta a Konföderációt és a világot. Leopold koronaherceg közelgő házassága Katharina von Richterrel nagy öröm pillanata a Császári Ház és a Konföderáció számára egyaránt.",
    "emperor.titles.label": "Teljes Stílus és Címek",
    "emperor.titles.text": "Őcsászári és Királyi Felsége II. Miksa, Isten Kegyelméből Ausztria-Duna Császára, a Dunai Országok Királya, Neustadt Főhercege, a Keleti Őrgrófságok Nagyhercege, a Folyóvidéki Népek Védelmezője, az Arany Sas Rend Lovagja.",
    "pillars.tradition.text": "1917 óta a Császári Ház fenntartja a Dunai Konföderáció szertartási hagyományait — az éves Sas Ünneptől a Császár ünnepélyes Kihirdetéséig a Hofburg erkélyéről és az ősi Magyar Koronázásig Budapesten.",
    "pillars.honour.text": "Az Arany Sas Rend, amelyet 1917-ben alapítottak a Dunai Föderáció kihirdetésekor, továbbra is a legmagasabb kitüntetés, amelyet a Császár adományozhat. Kitüntetettjei között államférfiak, tudósok és harcosok találhatók, akik kiválóan szolgálták a dunai népeket.",
    "pillars.legacy.text": "A Habsburg-Lotaringiai Ház hét évszázadon át adott császárokat, királyokat és főhercegeket. 1917 óta, mint Ausztria-Duna Császári Ház, a Dunai Konföderációt vezette a huszadik század megrázkódtatásain át a jelenkorig.",
    "palace.title": "Palais Danubio",
    "palace.text": "1919 és 1925 között épült a Duna nyugati partján. A Palais Danubio a Dunai Tanács székhelye — a Konföderáció hét tagállamának kormányzóiból álló gyűlés. Amikor a kormányzók Bécsben üléseznek, a Palais Danubio a hivatalos találkozóhelyük, amelynek Nagy Tanácsterme a Föderációt irányító tanácskozások helyszíne.",
    "timeline.1914.event": "Szarajevó: A Főherceg Túléli",
    "timeline.1914.desc": "A Ferenc Ferdinánd főherceg elleni merénylet Szarajevóban kudarcot vall. A főherceg megsebesül, de túléli. Az európai válságot diplomáciával fékezik meg, elkerülve a szélesebb konfliktust.",
    "timeline.1917.event": "Bécsi Szerződés és a Dunai Föderáció",
    "timeline.1917.desc": "I. Ferenc Ferdinánd császár aláírja a bécsi szerződést, az Osztrák-Magyar Monarchiát tizennégy tagállamból és társult királyságokból álló Dunai Föderációvá alakítva — új alkotmányos rendet teremtve Közép-Európa számára.",
    "timeline.1923.event": "A Föderációs Korona Elkészül",
    "timeline.1923.desc": "A Föderációs Korona, amelyet I. Ferenc Ferdinánd császár 1920-ban rendelt meg, három év kézműves munka után elkészül platinából, gyöngyökből, gyémántokból, rubinokból, zafírokból és smaragdokból.",
    "timeline.1998.event": "II. Miksa Trónra Lépése",
    "timeline.1998.desc": "A jelenlegi császár trónra lép, megkezdve egy diplomáciai megújulással, kulturális mecénássággal és a Konföderáció intézményeinek modernizálásával jellemzett uralkodást.",
    "timeline.2000.event": "Tragédia a Párizsi Ritzben",
    "timeline.2000.desc": "A néhai Mária-Krisztina császárné a párizsi Ritz szálloda tűzvészében veszti életét szeptember 10-én. A Császár sztoikus gyásza és folytatódó szolgálata uralkodásának meghatározó pillanatává válik.",
    "timeline.2026.event": "A Császári Eljegyzés",
    "timeline.2026.desc": "Leopold von Habsburg koronaherceg és Katharina von Richter kisasszony bejelentik eljegyzésüket, nagy örömet hozva a Konföderációnak.",
    "press.pretitle": "Die Wiener Eleganz · Udvari Szezon Különszám",
    "press.subtitle": "2026. január. Kétezer vendég. Egy éjszaka. Az Udvari Bál visszatér a Hofburgba — és semmi sem olyan, mint volt.",
    "press.img1": "A Császári Menet · Hofburg, 2026. január",
    "press.img2": "A Hofburg Felett · 360 Drón · 2026. január",
    "press.img3": "A Bonbonnière · Wiener Werkstätte Neu · 2026",
  },
  cs: {
    "nav.home": "Úvod",
    "nav.history": "Historie",
    "nav.family": "Císařská Rodina",
    "nav.traditions": "Tradice",
    "nav.heraldry": "Heraldika",
    "nav.properties": "Císařské Rezidence",
    "nav.world": "Svět",
    "nav.constitution": "Ústava",
    "nav.books": "Dunajský Trůn",
    "nav.press": "Tisk",
    "nav.transparency": "Transparentnost",
    "nav.news": "Zprávy",
    "header.imperialHouse": "Císařský Dům",
    "hero.pretitle": "Zal. MCMXVII · Neustadt, Dunaj",
    "hero.title1": "Císařský Dům",
    "hero.title2": "Rakousko-Dunaj",
    "hero.subtitle": "Strážci Dunaje. Dědicové tisíciletí.",
    "hero.cta1": "Naše Historie",
    "hero.cta2": "Císařská Rodina",
    "hero.scroll": "Posuňte",
    "about.section": "I · Dům",
    "about.title1": "Dynastie zrozená",
    "about.title2": "z Orla a Řeky",
    "about.link": "Celá historie →",
    "emperor.section": "II · Panovník",
    "emperor.title": "Jeho Císařské Veličenstvo",
    "emperor.link": "Císařská Rodina →",
    "pillars.section": "III · Naše Základy",
    "pillars.title": "Tři Pilíře Domu",
    "pillars.tradition.title": "Tradice",
    "pillars.honour.title": "Čest",
    "pillars.legacy.title": "Odkaz",
    "pillars.link": "Více →",
    "palace.section": "IV · Rezidence",
    "timeline.section": "V · Klíčová Data",
    "timeline.title": "Milníky Dynastie",
    "timeline.link": "Celá historie →",
    "press.title": "Ples, který nikdy nekončí",
    "press.link": "Celý článek →",
    "announcement": "✦   Císařské oznámení: Zasnoubení korunního prince Leopolda von Habsburg a slečny Kathariny von Richter je slavnostně vyhlášeno — Jaro 2026   ✦",
    "about.p1": "Císařský dům Rakousko-Dunaj je pokračováním starobylého Domu Habsbursko-Lotrinského, jedné z nejslavnějších dynastií evropské historie. Jeho kořeny sahají k středověkým hrabatům z Habsburku a staletím císařů Svaté říše římské, králů Uher a Čech a arcivévodů rakouských. V roce 1914 selhal pokus o atentát na arcivévodu Františka Ferdinanda v Sarajevu — arcivévoda přežil a evropská krize byla vyřešena u jednacího stolu. Vídeňská smlouva z roku 1917 přeměnila Rakousko-Uherskou monarchii na Dunajskou federaci.",
    "about.p2": "Dnes, pod vládou Jeho Císařského a Královského Apoštolského Veličenstva Císaře Maxmiliána I. — nyní v devatenáctém roce na trůnu — Dům nadále slouží jako ústavní suverén Dunajské konfederace, vládnoucí čtrnácti členským státům, dvěma přidruženým královstvím a více než osmdesáti milionům občanů.",
    "emperor.caption": "Jeho Císařské Veličenstvo Maxmilián II.\nCísař Rakouska-Dunaje · 37 let na trůnu",
    "emperor.p1": "Narozen v roce 1954 v císařském paláci Hofburg ve Vídni, Maxmilián František Josef Karel Rakousko-Dunajský nastoupil na Císařský trůn po smrti svého otce. Vládne již třicet sedm let.",
    "emperor.p2": "Jeho Veličenstvo neslo své povinnosti s neochvějnou důstojností tváří v tvář hluboké osobní tragédii. Zesnulá Císařovna Maria-Cristina zahynula při požáru pařížského Ritzu 10. září 2000. Nadcházející sňatek korunního prince Leopolda s Katharinou von Richter je momentem velké radosti.",
    "emperor.titles.label": "Plný Styl & Tituly",
    "emperor.titles.text": "Jeho Císařské a Královské Veličenstvo Maxmilián II., z Boží milosti Císař Rakouska-Dunaje, Král Dunajských zemí, Arcivévoda z Neustadtu, Velkovévoda Východních marek, Ochránce Říčních národů, Rytíř Řádu Zlatého orla.",
    "pillars.tradition.text": "Od roku 1917 Císařský dům udržuje ceremoniální tradice Dunajské konfederace — od výroční Slavnosti orla po slavnostní Proklamaci Císaře z balkonu Hofburgu a starobylou Uherskou korunovaci v Budapešti.",
    "pillars.honour.text": "Řád Zlatého orla, založený v roce 1917 při proklamaci Dunajské federace, zůstává nejvyšší poctou, kterou může Císař udělit.",
    "pillars.legacy.text": "Dům Habsbursko-Lotrinský vydal císaře, krále a arcivévody po sedm století. Od roku 1917, jako Císařský dům Rakousko-Dunaj, vedl Dunajskou konfederaci skrze převraty dvacátého století.",
    "palace.text": "Postavený mezi lety 1919 a 1925 podél západního břehu Dunaje, Palác Danubio slouží jako sídlo Dunajské rady — shromáždění guvernérů sedmi konstitučních států Konfederace.",
    "timeline.1914.event": "Sarajevo: Arcivévoda přežívá",
    "timeline.1914.desc": "Pokus o atentát na arcivévodu Františka Ferdinanda v Sarajevu selhává. Arcivévoda je zraněn, ale přežívá. Evropská krize je zvládnuta diplomacií.",
    "timeline.1917.event": "Vídeňská smlouva & Dunajská federace",
    "timeline.1917.desc": "Císař František Ferdinand I. podepisuje Vídeňskou smlouvu, přeměňující Rakousko-Uherskou monarchii na Dunajskou federaci čtrnácti členských států s přidruženými královstvími.",
    "timeline.1923.event": "Federační koruna dokončena",
    "timeline.1923.desc": "Federační koruna, zadaná Císařem Františkem Ferdinandem I. v roce 1920, je dokončena po třech letech řemeslné práce v platině, perlách, diamantech, rubínech, safírech a smaragdech.",
    "timeline.1998.event": "Nástup Maxmiliána I.",
    "timeline.1998.desc": "Současný Císař nastupuje na trůn, zahajuje vládu poznamenanou diplomatickou obnovou a modernizací institucí.",
    "timeline.2000.event": "Tragédie v pařížském Ritzu",
    "timeline.2000.desc": "Zesnulá Císařovna Maria-Cristina hyne při požáru pařížského Ritzu 10. září. Stoický smutek Císaře se stává určujícím momentem jeho vlády.",
    "timeline.2026.event": "Císařské zasnoubení",
    "timeline.2026.desc": "Korunní princ Leopold von Habsburg a slečna Katharina von Richter oznamují své zasnoubení, přinášejíce velkou radost Konfederaci.",
    "press.pretitle": "Die Wiener Eleganz · Speciální příloha dvorní sezóny",
    "press.subtitle": "Leden 2026. Dva tisíce hostů. Jedna noc. Dvorní ples se vrací do Hofburgu — a nic už není jako dřív.",
    "press.img1": "Císařský průvod · Hofburg, leden 2026",
    "press.img2": "Nad Hofburgem · 360 dronů · leden 2026",
    "press.img3": "Bonboniéra · Wiener Werkstätte Neu · 2026",
  },
  hr: {
    "nav.home": "Početna",
    "nav.history": "Povijest",
    "nav.family": "Carska Obitelj",
    "nav.traditions": "Tradicije",
    "nav.heraldry": "Heraldika",
    "nav.properties": "Carske Rezidencije",
    "nav.world": "Svijet",
    "nav.constitution": "Ustav",
    "nav.books": "Dunavski Prijestolje",
    "nav.press": "Tisak",
    "nav.transparency": "Transparentnost",
    "nav.news": "Vijesti",
    "header.imperialHouse": "Carski Dom",
    "hero.pretitle": "Osn. MCMXVII · Neustadt, Dunav",
    "hero.title1": "Carski Dom",
    "hero.title2": "Austrija-Dunav",
    "hero.subtitle": "Čuvari Dunava. Nasljednici tisućljeća.",
    "hero.cta1": "Naša Povijest",
    "hero.cta2": "Carska Obitelj",
    "hero.scroll": "Pomicanje",
    "about.section": "I · Dom",
    "about.title1": "Dinastija rođena",
    "about.title2": "od Orla i Rijeke",
    "about.link": "Cijela povijest →",
    "emperor.section": "II · Vladar",
    "emperor.title": "Njegovo Carsko Veličanstvo",
    "emperor.link": "Carska Obitelj →",
    "pillars.section": "III · Naši Temelji",
    "pillars.title": "Tri Stupa Doma",
    "pillars.tradition.title": "Tradicija",
    "pillars.honour.title": "Čast",
    "pillars.legacy.title": "Naslijeđe",
    "pillars.link": "Više →",
    "palace.section": "IV · Rezidencija",
    "timeline.section": "V · Ključni Datumi",
    "timeline.title": "Prekretnice Dinastije",
    "timeline.link": "Cijela povijest →",
    "press.title": "Bal koji nikada ne završava",
    "press.link": "Cijeli članak →",
    "announcement": "✦   Carsko priopćenje: Zaruke prijestolonasljednika Leopolda von Habsburga i gospođice Katharine von Richter svečano su proglašene — Proljeće 2026.   ✦",
    "about.p1": "Carski dom Austrija-Dunav je nastavak drevnog Doma Habsburg-Lotarinški, jedne od najslavnijih dinastija europske povijesti. Korijeni sežu do srednjovjekovnih grofova Habsburških i stoljeća careva Svetog Rimskog Carstva, kraljeva Ugarske i Češke te nadvojvoda Austrije. 1914. pokušaj atentata na nadvojvodu Franju Ferdinanda u Sarajevu propao je — nadvojvoda je preživio, a europska kriza riješena je za pregovaračkim stolom. Bečki ugovor iz 1917. pretvorio je Austro-Ugarsku monarhiju u Dunavsku Federaciju.",
    "about.p2": "Danas, pod vladavinom Njegova Carskog i Kraljevskog Apostolskog Veličanstva Cara Maksimilijana I. — sada u devetnaestoj godini na prijestolju — Dom nastavlja služiti kao ustavni suveren Dunavske Konfederacije, vladajući nad četrnaest država članica, dva pridružena kraljevstva i više od osamdeset milijuna građana.",
    "emperor.caption": "Njegovo Carsko Veličanstvo Maksimilijan II.\nCar Austrije-Dunava · 37 godina na prijestolju",
    "emperor.p1": "Rođen 1954. u carskoj palači Hofburg u Beču, Maksimilijan Franz Josef Karl Austrijsko-Dunavski stupio je na Carsko prijestolje nakon smrti svog oca. Vlada već trideset sedam godina.",
    "emperor.p2": "Njegovo Veličanstvo nosilo je svoje dužnosti s nepokolebljivim dostojanstvom suočeno s dubokom osobnom tragedijom. Pokojna Carica Maria-Cristina stradala je u požaru pariškog Ritza 10. rujna 2000. Nadolazeći brak prijestolonasljednika Leopolda s Katharinom von Richter je trenutak velike radosti.",
    "emperor.titles.label": "Puni Stil & Titule",
    "emperor.titles.text": "Njegovo Carsko i Kraljevsko Veličanstvo Maksimilijan II., Božjom milošću Car Austrije-Dunava, Kralj Dunavskih zemalja, Nadvojvoda od Neustadta, Veliki vojvoda Istočnih marki, Zaštitnik Riječnih naroda, Vitez Reda Zlatnog orla.",
    "pillars.tradition.text": "Od 1917. Carski dom održava ceremonijalne tradicije Dunavske Konfederacije — od godišnje Svečanosti orla do svečane Proklamacije Cara s balkona Hofburga i drevne Ugarske krunidbe u Budimpešti.",
    "pillars.honour.text": "Red Zlatnog orla, osnovan 1917. pri proglašenju Dunavske Federacije, ostaje najviše odlikovanje koje Car može dodijeliti.",
    "pillars.legacy.text": "Dom Habsburg-Lotarinški iznjedrio je careve, kraljeve i nadvojvode tijekom sedam stoljeća. Od 1917., kao Carski dom Austrija-Dunav, vodio je Dunavsku Konfederaciju kroz previranja dvadesetog stoljeća.",
    "palace.text": "Izgrađen između 1919. i 1925. uz zapadnu obalu Dunava, Palača Danubio služi kao sjedište Dunavskog vijeća — skupštine guvernera sedam sastavnih država Konfederacije.",
    "timeline.1914.event": "Sarajevo: Nadvojvoda preživljava",
    "timeline.1914.desc": "Pokušaj atentata na nadvojvodu Franju Ferdinanda u Sarajevu propada. Nadvojvoda je ranjen, ali preživljava. Europska kriza obuzdana je diplomacijom.",
    "timeline.1917.event": "Bečki ugovor & Dunavska Federacija",
    "timeline.1917.desc": "Car Franjo Ferdinand I. potpisuje Bečki ugovor, pretvarajući Austro-Ugarsku monarhiju u Dunavsku Federaciju četrnaest država članica s pridruženim kraljevstvima.",
    "timeline.1923.event": "Federacijska kruna dovršena",
    "timeline.1923.desc": "Federacijska kruna, naručena od Cara Franje Ferdinanda I. 1920., dovršena je nakon tri godine obrtničkog rada u platini, biserima, dijamantima, rubinima, safirima i smaragdima.",
    "timeline.1998.event": "Stupanje Maksimilijana I.",
    "timeline.1998.desc": "Sadašnji Car stupa na prijestolje, započinjući vladavinu obilježenu diplomatskom obnovom i modernizacijom institucija.",
    "timeline.2000.event": "Tragedija u pariškom Ritzu",
    "timeline.2000.desc": "Pokojna Carica Maria-Cristina strada u požaru pariškog Ritza 10. rujna. Stoička žalost Cara postaje određujući trenutak njegove vladavine.",
    "timeline.2026.event": "Carske zaruke",
    "timeline.2026.desc": "Prijestolonasljednik Leopold von Habsburg i gospođica Katharina von Richter objavljuju svoje zaruke, donoseći veliku radost Konfederaciji.",
    "press.pretitle": "Die Wiener Eleganz · Posebni prilog dvorske sezone",
    "press.subtitle": "Siječanj 2026. Dvije tisuće gostiju. Jedna noć. Dvorski bal vraća se u Hofburg — i ništa više nije kao prije.",
    "press.img1": "Carski kortež · Hofburg, siječanj 2026.",
    "press.img2": "Iznad Hofburga · 360 dronova · siječanj 2026.",
    "press.img3": "Bonbonijera · Wiener Werkstätte Neu · 2026.",
  },
  es: {
    "nav.home": "Inicio",
    "nav.history": "Historia",
    "nav.family": "La Familia Imperial",
    "nav.traditions": "Tradiciones",
    "nav.heraldry": "Heráldica",
    "nav.properties": "Residencias Imperiales",
    "nav.world": "El Mundo",
    "nav.constitution": "Constitución",
    "nav.press": "Prensa",
    "nav.transparency": "Transparencia",
    "nav.news": "Noticias",
    "nav.books": "El Trono del Danubio",
    "hero.pretitle": "Fundada MCMXVII · Neustadt, Danubio",
    "hero.title1": "Casa Imperial",
    "hero.title2": "Austria-Danubio",
    "hero.subtitle": "Guardianes del Danubio. Herederos de un milenio.",
    "hero.motto": "Aquila et Flumen in Aeternum",
    "hero.cta1": "Nuestra Historia",
    "hero.cta2": "La Familia Imperial",
    "hero.scroll": "Desplazar",
    "about.pretitle": "Desde 1917",
    "about.title": "Una Dinastía Forjada por la Historia",
    "about.p1": "La Casa Imperial de Austria-Danubio traza su linaje a través de más de un milenio de gobierno de los Habsburgo, pero su forma moderna nació del crisol de la crisis de 1914.",
    "about.p2": "El Tratado de Viena de 1917 creó la Federación del Danubio — una unión constitucional de catorce estados constituyentes, dos reinos asociados y un protectorado.",
    "emperor.pretitle": "El Emperador Reinante",
    "emperor.title": "Su Majestad Imperial y Real Apostólica",
    "emperor.name": "Emperador Maximiliano II",
    "emperor.subtitle": "Emperador de Austria · Gran Duque del Danubio",
    "emperor.caption": "Su Majestad Imperial Maximiliano II\nEmperador de Austria-Danubio · 37 años en el trono",
    "emperor.p1": "Maximiliano II ascendió al trono en 1989 tras la muerte de su padre, el Emperador Federico I. En sus treinta y siete años de reinado, ha guiado la Federación a través de una profunda transformación.",
    "emperor.p2": "Viudo desde la trágica muerte de la Emperatriz María-Cristina en el incendio del Ritz de París en el año 2000, el Emperador ha dedicado su vida al servicio de la Federación.",
    "emperor.titles.label": "Estilo y Títulos Completos",
    "emperor.titles.text": "Su Majestad Imperial y Real Apostólica Maximiliano II, por la Gracia de Dios Emperador de Austria-Danubio, Rey de las Tierras del Danubio, Archiduque de Neustadt, Gran Duque de las Marcas Orientales.",
    "pillar1.title": "Tradición",
    "pillar1.text": "Mil años de gobierno de los Habsburgo, adaptados al mundo moderno.",
    "pillar2.title": "Honor",
    "pillar2.text": "El Código Imperial exige servicio por encima de privilegio.",
    "pillar3.title": "Legado",
    "pillar3.text": "Cada generación construye sobre los cimientos de la anterior.",
    "pillars.tradition.text": "Desde 1917, la Casa Imperial mantiene las tradiciones ceremoniales de la Confederación del Danubio.",
    "pillars.honour.text": "La Orden del Águila Dorada, fundada en 1917, sigue siendo la más alta distinción que el Emperador puede conceder.",
    "pillars.legacy.text": "La Casa de Habsburgo-Lorena ha producido emperadores, reyes y archiduques durante siete siglos.",
    "palace.pretitle": "Residencia Imperial",
    "palace.title": "El Hofburg, Neustadt",
    "palace.text": "Sede del gobierno imperial desde 1920, el Hofburg de Neustadt es tanto palacio de trabajo como símbolo de la unidad federal.",
    "timeline.pretitle": "Hitos",
    "timeline.title": "Momentos que Definieron la Federación",
    "timeline.link": "Historia completa →",
    "timeline.1914.event": "Sarajevo: El Archiduque Sobrevive",
    "timeline.1914.desc": "Francisco Fernando sobrevive al atentado de Sarajevo, cambiando el curso de la historia.",
    "timeline.1917.event": "Tratado de Viena",
    "timeline.1917.desc": "Se establece la Federación del Danubio como unión constitucional de catorce estados.",
    "timeline.1923.event": "La Corona de la Federación",
    "timeline.1923.desc": "Se completa la Corona de la Federación con catorce torres representando cada estado.",
    "timeline.1998.event": "Ascenso de Maximiliano II",
    "timeline.1998.desc": "El actual Emperador asciende al trono, iniciando un reinado de renovación diplomática.",
    "timeline.2000.event": "Tragedia en París",
    "timeline.2000.desc": "La Emperatriz María-Cristina perece en el incendio del Ritz de París.",
    "timeline.2026.event": "Compromiso Imperial",
    "timeline.2026.desc": "Se anuncia el compromiso del Príncipe Heredero Leopoldo con Katharina von Richter.",
    "press.pretitle": "Última Noticia",
    "press.title": "El Gran Baile de la Corte de 2026",
    "press.link": "Leer Artículo Completo →",
    "announcement": "✦   Comunicado Imperial: El compromiso del Príncipe Heredero Leopoldo von Habsburg con la Srta. Katharina von Richter ha sido proclamado solemnemente — Primavera 2026.   ✦",
      "about.link": "Leer la historia completa →",
    "about.section": "I · La Casa",
    "about.title1": "Una Dinastía nacida",
    "about.title2": "del Águila y el Río",
    "emperor.link": "Conocer a la Familia Imperial →",
    "emperor.section": "II · El Soberano",
    "header.imperialHouse": "Casa Imperial",
    "palace.section": "IV · La Residencia",
    "pillars.honour.title": "Honor",
    "pillars.legacy.title": "Legado",
    "pillars.link": "Saber más →",
    "pillars.section": "III · Nuestros Fundamentos",
    "pillars.title": "Los Tres Pilares de la Casa",
    "pillars.tradition.title": "Tradición",
    "press.img1": "El Cortejo Imperial · Hofburg, enero 2026",
    "press.img2": "Sobre el Hofburg · 360 drones · enero 2026",
    "press.img3": "La Bonbonnière · Wiener Werkstätte Neu · 2026",
    "press.subtitle": "Enero 2026. Dos mil invitados. Una noche. El Hofball.",
    "timeline.section": "V · Fechas Importantes",
},
};

// Merge all page translations into a single lookup
const allPageTranslations = [historyTranslations, familyTranslations, worldTranslations, constitutionTranslations, booksTranslations, footerTranslations, transparencyTranslations, traditionsTranslations, heraldryTranslations, propertiesTranslations, pressTranslations, newsTranslations];

function mergeTranslations(): Record<Language, Record<string, string>> {
  const langs: Language[] = ["de", "en", "fr", "hu", "cs", "hr", "es"];
  const merged = {} as Record<Language, Record<string, string>>;
  for (const lang of langs) {
    merged[lang] = { ...translations[lang] };
    for (const pageT of allPageTranslations) {
      if (pageT[lang]) {
        Object.assign(merged[lang], pageT[lang]);
      }
    }
  }
  return merged;
}

const allTranslations = mergeTranslations();

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [switching, setSwitching] = useState(false);
  const [language, setLanguageState] = useState<Language>(() => {
    // Check URL parameter first
    const urlParams = new URLSearchParams(window.location.search);
    const urlLang = urlParams.get("lang") as Language;
    if (urlLang && ["de","en","fr","hu","cs","hr","es"].includes(urlLang)) {
      localStorage.setItem("df-language", urlLang);
      return urlLang;
    }
    const saved = localStorage.getItem("df-language");
    return (saved as Language) || "de";
  });

  const setLanguage = useCallback((lang: Language) => {
    setSwitching(true);
    setTimeout(() => {
    setLanguageState(lang);
    localStorage.setItem("df-language", lang);
      setSwitching(false);
    }, 150);
  }, []);

  const t = useCallback(
    (key: string): string => {
      // Try current language, fallback to German, then English, then key
      return allTranslations[language]?.[key] || allTranslations.de[key] || allTranslations.en[key] || key;
    },
    [language]
  );

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, switching }}>
      {children}
    </LanguageContext.Provider>
  );
}
